before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rails db:reset
language: ruby
rvm:
  - 2.6.3
services:
  - postgresql
