env:
  global:
    - CC_TEST_REPORTER_ID=2b140cabf7f3e78c925044464b83c889bd60b58167bc35327cd280a00cf00215
language: ruby
rvm:
  - 2.6.3
services:
  - postgresql

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rails db:reset
script:
  - bundle exec rake db:setup
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT
