version: '3.7'

services:
  web:
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=[password]
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
