version: '3.7'

services:
  spring:
    image: jahmali/rebels_manager:v1
    build:
      context: .
    command: spring server
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_ENV
    volumes:
      - ./:/usr/src/app
      - gems:/usr/local/bundle
      - node-modules:/usr/src/app/node_modules
      - ${HOME}/.irbrc:/root/.irbrc
      - ${HOME}/.irb-history:/root/.irb-history

  webpacker:
    image: jahmali/rebels_manager:v1
    command: ./bin/webpack-dev-server
    volumes:
      - ./:/usr/src/app
      - gems:/usr/local/bundle
      - node-modules:/usr/src/app/node_modules
    ports:
      - 3035:3035
